// Generated by scripts/write-changelog.ts during pnpm build. Do not edit by hand.

export type BuildChangelogItem = {
  en: string;
  id: string;
};

export type BuildChangelogEntry = {
  date: string;
  items: readonly BuildChangelogItem[];
};

export const buildChangelog: readonly BuildChangelogEntry[] = [
  {
    date: "2026-10-11",
    items: [
      { en: "Next milk and pumping cards were updated.", id: "Kartu jadwal susu dan pompa diperbarui." },
      { en: "A database change was added.", id: "Perubahan database ditambahkan." },
      { en: "The home screen was updated.", id: "Beranda diperbarui." },
      { en: "The latest milk, diaper, and pumping note is easier to see.", id: "Catatan terakhir susu, popok, dan pompa lebih mudah dilihat." },
      { en: "Other parts of the app were updated.", id: "Bagian lain aplikasi diperbarui." },
    ],
  },
  {
    date: "2026-10-10",
    items: [
      { en: "The latest milk, diaper, and pumping note is easier to see.", id: "Catatan terakhir susu, popok, dan pompa lebih mudah dilihat." },
      { en: "A database change was added.", id: "Perubahan database ditambahkan." },
      { en: "The home screen was updated.", id: "Beranda diperbarui." },
      { en: "Milk, diaper, and pumping summaries were updated.", id: "Ringkasan susu, popok, dan pompa diperbarui." },
      { en: "Diaper logging was updated.", id: "Catatan popok diperbarui." },
      { en: "The changelog was updated.", id: "Changelog diperbarui." },
      { en: "Other parts of the app were updated.", id: "Bagian lain aplikasi diperbarui." },
    ],
  },
];
